name: Charmed Life Film
favicon: null
layout_spectrum: 0.3324232641607523
typography_spectrum: 0.3620309664402157
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.46742097567766905
  lightness: 0.03319391096010804
  saturation: 0.5722157119307667
  rhythmicContrast: 0.9037295556627214
purpose: []
